#!/bin/sh

set -e;

sudo -v;

# Keep-alive: update existing `sudo` time stamp until `.osx` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

FT_HOME=`pwd`;

FT_GITHUB='git@github.com:Financial-Times';
FT_GITHUB_EXT='git';

PROJECTS=(next-service-registry next-config-vars kat-router kat-api kat-overview kat-myft kat-usage kat-client-proxies kmt-utilities kat-footer kmt-header)

LOCAL_APP_DIR_PREFIX="kat";
LOCAL_APP_NAME_PREFIX="ft-kat";
LOCAL_APPS=(api overview myft usage);

add_repos() {
    for project in "${PROJECTS[@]}"; do
        if [[ ! -d "./$project" ]]; then
            echo "adding $project:";

            git clone "$FT_GITHUB/$project.$FT_GITHUB_EXT";
        else
            echo "$project already exists, skipping.";
        fi
    done;
}

get_port_number() {
    PORT=`grep -E "^PORT=[0-9]{4}" "$FT_HOME/$1/.env"`;
    IFS="=" read -ra PORT_NUMBER <<< "$PORT";

    echo "${PORT_NUMBER[1]}";
}

setup_projects() {
    for project in "${PROJECTS[@]}"; do
        cd "$FT_HOME/$project";

        if [[ -f Makefile ]]; then
            rm -rf .env;

            make .env;

            make install;

            make build;
        fi

        cd "$FT_HOME";
    done;
}

setup_router() {
    cd "$FT_HOME/kat-router";

    echo "" >> .env;

    for local_app in "${LOCAL_APPS[@]}"; do
        port="$(get_port_number $LOCAL_APP_DIR_PREFIX-$local_app)";

        if [[ -z `grep -E "^$LOCAL_APP_NAME_PREFIX-$local_app=[0-9]{4}" "$FT_HOME/kat-router/.env"` ]]; then
            echo "adding $LOCAL_APP_NAME_PREFIX-$local_app=$port to .env";

            echo "$LOCAL_APP_NAME_PREFIX-$local_app=$port"  >> .env;
        else
            echo "$LOCAL_APP_NAME_PREFIX-$local_app already exists in .env";
        fi;

    done;

    cd "$FT_HOME";
}

update_hosts() {
    if [[ -z "$(sudo grep -E 'local\.ft\.com' /etc/hosts)" ]]; then
        echo "adding local.ft.com"

        sudo -- sh -c "echo '127.0.0.1	local.ft.com' >> /etc/hosts"
    else
        echo "/etc/hosts already contains: local.ft.com"
    fi
}

update_hosts;

add_repos;

setup_projects;

setup_router;