#!/bin/sh

install_homebrew() {

    if [ -x "$(which brew)" ]; then

        echo "Homebrew is already installed";

    else

        echo "Installing Homebrew";

        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

    fi;

}

install_homebrew_defaults() {
    # Install GNU core utilities (those that come with OS X are outdated)
    brew install coreutils
    # Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
    brew install findutils

    brew install bash

    # Install wget with PCRE support
    brew install --with-pcre git
    brew install git-extras

    # Install wget with IRI support
    brew install wget --with-iri

    # Install more recent versions of some OS X tools
    brew tap homebrew/dupes
    brew install homebrew/dupes/grep

    brew install ack
    brew install rename
    brew install tree

    # Install most current versions of languages
    brew install go
    brew install python

    # Install PaaS CLIs
    brew install awscli
    brew install heroku

    # Install media editing stuff
    brew install jpegoptim
    brew install jpeg
    brew install freetype
    brew install libpng
    brew install libtiff
    brew install imagemagick
    brew install graphicsmagick
    brew install ffmpeg

    # Install docker(-*)
    brew install docker
    brew install docker-machine
    brew install docker-compose
    brew install docker-swarm

    # Install services for their binaries
    brew install neo4j
    brew install redis
    brew install postgresql
    brew install sqlite
    brew install voltdb

    # Install the rest
    brew install libyaml
    brew install openssl
    brew install xz
}


install_homebrew_default_casks() {
    # uncomment what you want to install

### Bringing command line like power to your GUI.
#    brew cask install alfred
#    brew cask install atom
    brew cask install google-chrome
### easily update to the latest version of Java
    brew cask install java
#    brew cask install spotify
#    brew cask install android-file-transfer
#    brew cask install google-drive
### adds markdown rendering to your Finder's QuickLook: https://github.com/toland/qlmarkdown
    brew cask install qlmarkdown
    brew cask install postman
#    brew cask install sublime-text
#    brew cask install firefox
    brew cask install google-hangouts
#    brew cask install skype
    brew cask install virtualbox
### installs the `Adobe Source Code Pro` font: specifically designed for developers/IDEs
    brew cask install font-source-code-pro
### Better `Terminal`, allows for multiple panes per Tab/Window and a bunch of other nice customisations
    brew cask install iterm2
    brew cask install slack
#    brew cask install webstorm
}